version: 2
updates:
# # Fetch and update latest `npm` packages
# - package-ecosystem: npm
#   directory: '/'
#   schedule:
#     interval: weekly
#     time: '00:00'
#   open-pull-requests-limit: 10
#   reviewers:
#     - ebfvince
#   assignees:
#     - ebfvince
#   commit-message:
#     prefix: '⬆ fix'
#     prefix-development: '⬆️ chore'
#     include: scope

# Fetch and update latest `github-actions` pkgs
- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: weekly
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - ebfvince
  assignees:
    - ebfvince
  commit-message:
    prefix: '⬆ fix'
    prefix-development: '⬆️ chore'
    include: scope
